name: Test Workflow

on:
  issue_comment:
    types: [created]

jobs:
  test:
    # Pull Requestのコメントかつ、コメントが「tests」の場合のみ実行
    if: github.event.issue.pull_request && contains(github.event.comment.body, 'tests')
    runs-on: ubuntu-latest
    
    steps:
      - name: Get PR information
        id: pr_info
        uses: actions/github-script@v7
        with:
          script: |
            const pr = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            });
            return pr.data.head.sha;
          result-encoding: string
      
      - name: Echo PR branch SHA
        run: |
          echo "PR branch latest SHA: ${{ steps.pr_info.outputs.result }}"
